import {describe,it,expect} from 'vitest';
import {pocketWatch} from '../src/content/items/pocketWatch';
import {ValuationSystem} from '../src/systems/ValuationSystem';
import {EconomySystem} from '../src/systems/EconomySystem';
import {createDefaultState} from '../src/content/defaultState';
import {GameFlow} from '../src/core/GameFlow';
import {SaveService} from '../src/services/SaveService';
import {Game} from '../src/app/Game';
import type {GameState} from '../src/core/types';

const defaultItem = () => ({definitionId:pocketWatch.id,discoveredClueIds:[],condition:42,completed:false,owned:false,bought:false,sold:false,toolProgress:0});

describe('ValuationSystem',()=>{it('narrows value after 925 clue',()=>{const system=new ValuationSystem();const before=system.evaluate(pocketWatch,defaultItem());expect([before.knownMin,before.knownMax]).toEqual([20,80]);const after=system.evaluate(pocketWatch,{...defaultItem(),discoveredClueIds:['silver_925']});expect([after.knownMin,after.knownMax]).toEqual([70,150]);});});
describe('EconomySystem',()=>{it('enforces affordability and exact spend',()=>{const state=createDefaultState();const economy=new EconomySystem(state);expect(economy.spend(140,'purchase_item')).toBe(false);expect(state.player.cash).toBe(100);expect(economy.spend(40,'purchase_item')).toBe(true);expect(state.player.cash).toBe(60);expect(economy.spend(40,'duplicate')).toBe(true);expect(state.player.cash).toBe(20);});it('earns sale only when caller changes ownership once',()=>{const state=createDefaultState();const economy=new EconomySystem(state);expect(economy.earn(118,'sell_item')).toBe(true);expect(state.player.cash).toBe(218);});});
describe('GameFlow',()=>{it('rejects invalid direct sale',()=>{const flow=new GameFlow('TITLE');expect(()=>flow.transition('SELL')).toThrow();flow.transition('WORKSHOP');expect(()=>flow.transition('SELL')).toThrow();});});
class MemoryAdapter {value:string|null=null;async init(){}getPlatformName(){return 'web'}getLanguage(){return 'en'}async loadSave(){return this.value}async save(data:string){this.value=data}}
describe('SaveService',()=>{it('recovers empty and corrupt saves',async()=>{const adapter=new MemoryAdapter();const service=new SaveService(adapter);expect((await service.load()).player.cash).toBe(100);adapter.value='{bad';expect((await service.load()).player.cash).toBe(100);});it('migrates partial old save',async()=>{const adapter=new MemoryAdapter();adapter.value=JSON.stringify({version:0,player:{cash:25}});const state=await new SaveService(adapter).load();expect(state.saveVersion).toBe(1);expect(state.player.cash).toBe(25);expect(state.stats.itemsSold).toBe(0);});});
describe('Game transactions',()=>{it('buys and sells the pocket watch exactly once',async()=>{const store=new Map<string,string>();Object.defineProperty(globalThis,'localStorage',{configurable:true,value:{getItem:(key:string)=>store.get(key)??null,setItem:(key:string,value:string)=>{store.set(key,value);}}});Object.defineProperty(globalThis,'navigator',{configurable:true,value:{language:'en'}});const game=await new Game().init();await game.start();await game.start();await game.showClient();await game.inspect();await game.revealClue();await game.decideBack();expect(await game.buy()).toBe(true);expect(game.state.player.cash).toBe(60);expect(await game.buy()).toBe(false);game.selectTool('brush');for(let i=0;i<5;i++)await game.stroke();game.selectTool('polish');for(let i=0;i<4;i++)await game.stroke();await game.toSell();expect(await game.sell()).toBe(true);expect(game.state.player.cash).toBe(178);expect(await game.sell()).toBe(false);});});
