import {describe,it,expect} from 'vitest';
import {pocketWatch} from '../src/content/items/pocketWatch';
import {vintageCamera} from '../src/content/items/vintageCamera';
import {fakeLuxuryWatch} from '../src/content/items/fakeLuxuryWatch';
import {pixelBox} from '../src/content/items/pixelBox';
import {painting} from '../src/content/items/painting';
import {itemSequence} from '../src/content/items';
import {ValuationSystem} from '../src/systems/ValuationSystem';
import {EconomySystem} from '../src/systems/EconomySystem';
import {createDefaultState} from '../src/content/defaultState';
import {GameFlow} from '../src/core/GameFlow';
import {SaveService} from '../src/services/SaveService';
import {Game} from '../src/app/Game';
import {RestorationSystem} from '../src/systems/RestorationSystem';
import type {GameState} from '../src/core/types';

describe('Restoration timing',()=>{it('applies seven second cleaning and five second polishing to every item',()=>{const system=new RestorationSystem();for(const definition of [pocketWatch,vintageCamera]){const item={...defaultItem(),definitionId:definition.id};system.selectTool(item,'brush');expect(system.work(definition,item,6999)).toBe(false);expect(system.work(definition,item,1)).toBe(true);system.selectTool(item,'polish');expect(system.work(definition,item,4999)).toBe(false);expect(system.work(definition,item,1)).toBe(true);expect(system.isComplete(definition,item)).toBe(true);}});});

const defaultItem = () => ({definitionId:pocketWatch.id,discoveredClueIds:[],condition:42,completed:false,owned:false,bought:false,sold:false,toolProgress:0});

describe('ValuationSystem',()=>{it('narrows value after 925 clue',()=>{const system=new ValuationSystem();const before=system.evaluate(pocketWatch,defaultItem());expect([before.knownMin,before.knownMax]).toEqual([20,80]);const after=system.evaluate(pocketWatch,{...defaultItem(),discoveredClueIds:['silver_925']});expect([after.knownMin,after.knownMax]).toEqual([70,150]);});});
describe('Vintage Camera',()=>{it('uses its own lens clue and valuation',()=>{const system=new ValuationSystem();const item={definitionId:vintageCamera.id,discoveredClueIds:['lens_coating'],condition:38,completed:false,owned:false,bought:false,sold:false,toolProgress:0};const value=system.evaluate(vintageCamera,item);expect([value.knownMin,value.knownMax]).toEqual([120,220]);expect(value.trueValue).toBe(176);});});
describe('Fake Luxury Watch',()=>{it('is registered before PixelBox and Painting and narrows on UV evidence',()=>{expect(itemSequence.map(item=>item.id)).toEqual(['pocket_watch_01','vintage_camera_01','fake_luxury_watch_01','pixel_box_84','painting_47']);const system=new ValuationSystem();const item={definitionId:fakeLuxuryWatch.id,discoveredClueIds:['uv_mark'],condition:34,completed:false,owned:false,bought:false,sold:false,toolProgress:0};const value=system.evaluate(fakeLuxuryWatch,item);expect([value.knownMin,value.knownMax]).toEqual([28,58]);expect(value.trueValue).toBe(42);});});
describe('PixelBox 84',()=>{it('offers a meaningful repair tradeoff before restoration',()=>{expect(pixelBox.repairOptions?.map(option=>[option.cost,option.valueBonus])).toEqual([[8,0],[24,38]]);expect(pixelBox.renderType).toBe('pixelBox');});});
describe('Painting',()=>{it('offers provenance clues and guaranteed versus risky sale routes',()=>{expect(painting.clues.map(clue=>clue.id)).toEqual(['provenance_card','gallery_stamp']);expect(painting.saleOptions?.map(option=>[option.id,option.successValue,option.fallbackValue,option.successChance])).toEqual([['dealer',190,190,1],['auction',285,105,.58]]);expect(painting.renderType).toBe('painting');});});
describe('EconomySystem',()=>{it('enforces affordability and exact spend',()=>{const state=createDefaultState();const economy=new EconomySystem(state);expect(economy.spend(140,'purchase_item')).toBe(false);expect(state.player.cash).toBe(100);expect(economy.spend(40,'purchase_item')).toBe(true);expect(state.player.cash).toBe(60);expect(economy.spend(40,'duplicate')).toBe(true);expect(state.player.cash).toBe(20);});it('earns sale only when caller changes ownership once',()=>{const state=createDefaultState();const economy=new EconomySystem(state);expect(economy.earn(118,'sell_item')).toBe(true);expect(state.player.cash).toBe(218);});});
describe('GameFlow',()=>{it('rejects invalid direct sale',()=>{const flow=new GameFlow('TITLE');expect(()=>flow.transition('SELL')).toThrow();flow.transition('WORKSHOP');expect(()=>flow.transition('SELL')).toThrow();});});
class MemoryAdapter {value:string|null=null;async init(){}getPlatformName(){return 'web'}getLanguage(){return 'en'}async loadSave(){return this.value}async save(data:string){this.value=data}}
describe('SaveService',()=>{it('recovers empty and corrupt saves',async()=>{const adapter=new MemoryAdapter();const service=new SaveService(adapter);expect((await service.load()).player.cash).toBe(100);adapter.value='{bad';expect((await service.load()).player.cash).toBe(100);});it('migrates partial old save',async()=>{const adapter=new MemoryAdapter();adapter.value=JSON.stringify({version:0,player:{cash:25}});const state=await new SaveService(adapter).load();expect(state.saveVersion).toBe(2);expect(state.player.cash).toBe(25);expect(state.stats.itemsSold).toBe(0);expect(state.progression.completedItemIds).toEqual([]);});});
describe('Game transactions',()=>{it('buys and sells the pocket watch exactly once',async()=>{const store=new Map<string,string>();Object.defineProperty(globalThis,'localStorage',{configurable:true,value:{getItem:(key:string)=>store.get(key)??null,setItem:(key:string,value:string)=>{store.set(key,value);}}});Object.defineProperty(globalThis,'navigator',{configurable:true,value:{language:'en'}});const game=await new Game().init();await game.start();await game.start();await game.showClient();await game.inspect();await game.revealClue();await game.decideBack();expect(await game.buy()).toBe(true);expect(game.state.player.cash).toBe(60);expect(await game.buy()).toBe(false);game.selectTool('brush');await game.stroke(7000);game.selectTool('polish');await game.stroke(5000);await game.toSell();expect(await game.sell()).toBe(true);expect(game.state.player.cash).toBe(178);expect(await game.sell()).toBe(false);});});
it('opens the vintage camera after the first item is sold',async()=>{const store=new Map<string,string>();Object.defineProperty(globalThis,'localStorage',{configurable:true,value:{getItem:(key:string)=>store.get(key)??null,setItem:(key:string,value:string)=>{store.set(key,value);}}});Object.defineProperty(globalThis,'navigator',{configurable:true,value:{language:'en'}});const game=await new Game().init();await game.start();await game.start();await game.showClient();await game.inspect();await game.revealClue();await game.decideBack();await game.buy();game.selectTool('brush');for(let i=0;i<5;i++)await game.stroke();game.selectTool('polish');for(let i=0;i<4;i++)await game.stroke();await game.toSell();await game.sell();await game.next();expect(game.phase).toBe('WORKSHOP');expect(await game.showClient()).toBe(true);expect(game.activeDefinition?.id).toBe(vintageCamera.id);await game.inspect();await game.revealClue();await game.decideBack();expect(await game.buy()).toBe(true);game.selectTool('brush');for(let i=0;i<5;i++)await game.stroke();game.selectTool('polish');for(let i=0;i<5;i++)await game.stroke();await game.toSell();expect(await game.sell()).toBe(true);expect(game.state.progression.completedItemIds).toEqual([pocketWatch.id,vintageCamera.id]);});
